import "./globals.css";
import { Hind_Siliguri } from "next/font/google";

const Hind = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Hind.className}>{children}</body>
    </html>
  );
}
